### ISSUE TITLE
Using default apache index.html instead of new index.php

### ISSUE THREAD

**Issue by DoctorCr4nk** [junglert/shc#16]
I just installed SHC on my RPI but I didnt got the website working, so i checked logs and directories and found out that in /var/www/html there was an index.html and index.php. I renamed the index.html to foo.html and it worked.

OS: Raspbian GNU/Linux 10 (buster)

**Comment by junglert** [comment]
I already know what the problem is and how to fix it.

Please be patient i am going to fix it asap

**Comment by junglert** [comment]
Changing deleting to renaming

**Comment by junglert** [comment]
https://github.com/junglert/shc/commit/c4a69fd0776a2eb6eaace7f02e49e8f6486f64cc
